import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { stat } from 'node:fs/promises';
import { MARKER, TARGETS, renderFor, targetByKey, type Target } from './targets.ts';

/** CLIs to install into when none are detected -- the two the tool is primarily aimed at. */
const FALLBACK_TARGETS = ['claude', 'opencode'];

export interface InitOptions {
  cwd: string;
  /** Explicit target keys. When omitted, detect from the project. */
  targets?: string[];
  /** Install for every known CLI regardless of detection. */
  all?: boolean;
  /** Overwrite a file we did not generate. */
  force?: boolean;
  dryRun?: boolean;
}

export type InitAction = 'created' | 'updated' | 'skipped-exists' | 'would-write';

export interface InitResult {
  installed: Array<{ target: string; file: string; action: InitAction }>;
  detected: string[];
  report: string;
}

async function exists(path: string): Promise<boolean> {
  try {
    await stat(path);
    return true;
  } catch {
    return false;
  }
}

async function detectTargets(cwd: string): Promise<Target[]> {
  const found: Target[] = [];
  for (const target of TARGETS) {
    if (await exists(join(cwd, target.detectDir))) found.push(target);
  }
  return found;
}

/** Ours if we generated it -- then updating is safe. Anything else needs --force. */
async function isOursOrMissing(path: string): Promise<'missing' | 'ours' | 'theirs'> {
  try {
    const text = await readFile(path, 'utf8');
    return text.includes(MARKER) ? 'ours' : 'theirs';
  } catch {
    return 'missing';
  }
}

export async function runInit(opts: InitOptions): Promise<InitResult> {
  const { cwd, targets: requested, all = false, force = false, dryRun = false } = opts;

  const detected = await detectTargets(cwd);
  let chosen: Target[];
  const notes: string[] = [];

  if (requested && requested.length > 0) {
    chosen = [];
    for (const key of requested) {
      const target = targetByKey(key);
      if (target) chosen.push(target);
      else notes.push(`unknown target "${key}" (known: ${TARGETS.map((t) => t.key).join(', ')})`);
    }
  } else if (all) {
    chosen = TARGETS;
  } else if (detected.length > 0) {
    chosen = detected;
  } else {
    chosen = FALLBACK_TARGETS.flatMap((k) => (targetByKey(k) ? [targetByKey(k) as Target] : []));
    notes.push('no AI CLI config directory found, so installed for Claude Code and opencode by default. Use --all or --target to change that.');
  }

  const installed: InitResult['installed'] = [];
  for (const target of chosen) {
    const path = join(cwd, target.file);
    const ownership = await isOursOrMissing(path);

    if (ownership === 'theirs' && !force) {
      installed.push({ target: target.key, file: target.file, action: 'skipped-exists' });
      continue;
    }
    if (dryRun) {
      installed.push({ target: target.key, file: target.file, action: 'would-write' });
      continue;
    }
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, renderFor(target), 'utf8');
    installed.push({ target: target.key, file: target.file, action: ownership === 'missing' ? 'created' : 'updated' });
  }

  return { installed, detected: detected.map((t) => t.key), report: buildReport(installed, notes) };
}

function buildReport(installed: InitResult['installed'], notes: string[]): string {
  const lines: string[] = ['RepoRadar installed.', ''];
  for (const entry of installed) {
    const label = targetByKey(entry.target)?.label ?? entry.target;
    const verb =
      entry.action === 'skipped-exists'
        ? 'skipped (file exists and was not generated by us -- pass --force to overwrite)'
        : entry.action === 'would-write'
          ? 'would write'
          : entry.action;
    lines.push(`  ${label.padEnd(16)} ${verb.padEnd(12)} ${entry.file}`);
  }
  lines.push('');
  for (const note of notes) lines.push(`  note: ${note}`);
  if (notes.length > 0) lines.push('');
  const wrote = installed.some((i) => i.action === 'created' || i.action === 'updated');
  if (wrote) {
    lines.push('Next: open your AI coding CLI in this project and run  /reporadar');
    lines.push('Or use it directly:  npx reporadar scan');
  }
  return lines.join('\n');
}
