import { JS, type Detector } from '../detector-types.ts';

/** String, date, version and tabular-data handling -- where naive implementations quietly corrupt data. */
export const DATA_DETECTORS: Detector[] = [
  {
    id: 'csv-parsing',
    capability: 'parsing CSV / delimited data',
    ext: JS,
    signals: [
      { name: 'comma-split', re: /\.split\(\s*['"`],['"`]\s*\)/ },
      { name: 'line-split', re: /\.split\(\s*(\/\u005cr\?\u005cn\/|['"`]\u005cn['"`])\s*\)/ },
      { name: 'csv-vocab', re: /\bcsv\b|\btsv\b|\bdelimiter\b|\bheaderRow\b/i },
    ],
    minSignals: 2,
    required: ['csv-vocab'],
    searchTerms: ['csv parser node quoted fields'],
    knownSolutions: ['papaparse', 'csv-parse', '@fast-csv/parse'],
    suppressIfDeps: ['papaparse', 'csv-parse', 'csv-parser', 'fast-csv', '@fast-csv/parse', 'neat-csv', 'd3-dsv'],
    note: 'CORRECTNESS: split(",") corrupts any row with a quoted field containing a comma, an escaped quote, or an embedded newline. This is silent data loss, not a style preference.',
    baseConfidence: 'high',
  },
  {
    id: 'semver-compare',
    capability: 'comparing semantic versions',
    ext: JS,
    signals: [
      { name: 'dot-split', re: /\.split\(\s*['"`]\.['"`]\s*\)/ },
      { name: 'version-vocab', re: /\b(version|semver|major|minor|patch)\b/i },
      { name: 'numeric-cast', re: /(parseInt|Number)\(/ },
    ],
    minSignals: 3,
    required: ['version-vocab'],
    searchTerms: ['semver compare node library'],
    knownSolutions: ['semver', 'semiver', 'compare-versions'],
    suppressIfDeps: ['semver', 'semiver', 'compare-versions'],
    note: 'Naive dot-split comparison mishandles prereleases (1.0.0-beta < 1.0.0), build metadata, and range syntax like ^1.2.3.',
    baseConfidence: 'medium',
  },
  {
    id: 'querystring-build',
    capability: 'building URL query strings',
    ext: JS,
    signals: [
      { name: 'encode', re: /encodeURIComponent\(/ },
      { name: 'amp-join', re: /\.join\(\s*['"`]&['"`]\s*\)/ },
    ],
    minSignals: 2,
    decisive: ['amp-join'],
    searchTerms: ['URLSearchParams nested query string'],
    knownSolutions: ['URLSearchParams (built-in)', 'qs', 'picoquery'],
    suppressIfDeps: ['qs', 'query-string', 'picoquery', 'fast-querystring'],
    note: 'URLSearchParams is built into the platform and gets encoding, repeated keys, and iteration right for free.',
    baseConfidence: 'medium',
  },
  {
    id: 'slugify',
    capability: 'slugifying strings for URLs',
    ext: JS,
    signals: [
      { name: 'slug-vocab', re: /\b(slug|slugify|toSlug|urlize|kebabCase)\b/i },
      { name: 'lower-replace-chain', re: /toLowerCase\(\)[\s\S]{0,150}\.replace\(/ },
      { name: 'nonword-strip', re: /replace\(\s*\/\[\^(a-z0-9|\u005cw)/i },
    ],
    minSignals: 2,
    required: ['slug-vocab'],
    searchTerms: ['slugify unicode transliteration'],
    knownSolutions: ['@sindresorhus/slugify', 'slugify', 'limax'],
    suppressIfDeps: ['slugify', '@sindresorhus/slugify', 'limax', 'speakingurl', 'url-slug'],
    note: 'Regex slugifiers strip non-Latin scripts and accented characters to nothing instead of transliterating them, so non-English titles collapse to empty slugs.',
    baseConfidence: 'medium',
  },
  {
    id: 'date-formatting',
    capability: 'formatting dates',
    ext: JS,
    signals: [
      { name: 'date-parts', re: /get(FullYear|Month|Date|Hours|Minutes|Seconds)\(\)/ },
      { name: 'pad', re: /padStart\(\s*2|padStart\(\s*4/ },
      { name: 'manual-concat', re: /\$\{[^}]*get(FullYear|Month|Date)|['"`]-['"`]\s*\+/ },
    ],
    minSignals: 2,
    required: ['date-parts'],
    searchTerms: ['date formatting library javascript', 'date-fns vs dayjs'],
    knownSolutions: ['Intl.DateTimeFormat (built-in)', 'date-fns', 'dayjs', 'luxon'],
    suppressIfDeps: ['date-fns', 'dayjs', 'luxon', 'moment', '@js-joda/core', '@internationalized/date'],
    note: 'Manual date string building ignores time zones and locales. Intl.DateTimeFormat is built in and handles both.',
    baseConfidence: 'low',
  },
];
