import { JS, type Detector } from '../detector-types.ts';

/** Plumbing where the Node platform, or one well-known package, has already solved it. */
export const PLATFORM_DETECTORS: Detector[] = [
  {
    id: 'argv-parsing',
    capability: 'command-line argument parsing',
    ext: JS,
    signals: [
      { name: 'argv-slice', re: /process\.argv\.slice\(\s*2\s*\)/ },
      { name: 'flag-prefix', re: /startsWith\(\s*['"`]--?/ },
      { name: 'eq-split', re: /\.split\(\s*['"`]=['"`]/ },
      { name: 'arg-loop', re: /for\s*\(\s*(let|const|var)\s+\w+\s+of\s+\w*[aA]rg/ },
    ],
    minSignals: 2,
    required: ['argv-slice'],
    searchTerms: ['cli argument parser node'],
    knownSolutions: ['node:util parseArgs (built-in)', 'citty', 'commander', 'cac'],
    suppressIfDeps: ['commander', 'yargs', 'minimist', 'cac', 'citty', 'meow', 'clipanion', 'oclif', 'arg', 'sade'],
    note: 'Node 20+ ships util.parseArgs, which covers flags, short options, and positionals with zero dependencies.',
    baseConfidence: 'medium',
  },
  {
    id: 'dotenv-parsing',
    capability: 'loading .env configuration files',
    ext: JS,
    signals: [
      { name: 'env-file', re: /['"`][^'"`\n]*\.env(\.[a-z]+)?['"`]/ },
      { name: 'eq-split', re: /\.split\(\s*['"`]=['"`]/ },
      { name: 'assign-process-env', re: /process\.env\[[^\]]+\]\s*=/ },
    ],
    minSignals: 2,
    required: ['env-file'],
    searchTerms: ['dotenv parser node env file'],
    knownSolutions: ['node --env-file (built-in)', 'dotenv', '@dotenvx/dotenvx'],
    suppressIfDeps: ['dotenv', '@dotenvx/dotenvx', 'dotenv-flow', 'dotenv-expand', 'env-var', 'envalid'],
    note: 'Naive parsers break on quoted values, multi-line values, escapes, and "export " prefixes. Node 20.6+ also supports --env-file natively.',
    baseConfidence: 'medium',
  },
  {
    id: 'custom-logger',
    capability: 'structured logging',
    ext: JS,
    signals: [
      { name: 'level-map', re: /\b(LOG_LEVELS|levels|LEVELS)\b\s*[:=]\s*[{[][^}\]]*\b(debug|info|warn|error)\b/ },
      { name: 'console-wrap', re: /console\.(log|info|warn|error|debug)\s*\(/ },
      { name: 'timestamp-prefix', re: /new Date\(\)\.toISOString\(\)/ },
      { name: 'logger-vocab', re: /\b(logger|createLogger|getLogger)\b/ },
    ],
    minSignals: 3,
    required: ['logger-vocab'],
    searchTerms: ['structured json logger node', 'pino vs winston'],
    knownSolutions: ['pino', 'consola', 'winston', 'tslog'],
    suppressIfDeps: ['pino', 'winston', 'consola', 'bunyan', 'tslog', 'loglevel', 'signale', 'debug', 'roarr'],
    note: 'A console wrapper gives you no structured JSON for log aggregators, no secret redaction, no child loggers, no transports, and no sampling under load.',
    baseConfidence: 'low',
  },
  {
    id: 'directory-walk',
    capability: 'recursive directory traversal / glob matching',
    ext: JS,
    signals: [
      { name: 'readdir', re: /readdir(Sync)?\s*\(/ },
      { name: 'recursion', re: /\b(walk|walkDir|traverse|crawl|collectFiles|getAllFiles)\s*\(/ },
      { name: 'ext-filter', re: /extname\(|endsWith\(\s*['"`]\./ },
    ],
    minSignals: 3,
    required: ['recursion'],
    searchTerms: ['fast glob node library'],
    knownSolutions: ['fs.glob (Node 22+ built-in)', 'tinyglobby', 'fast-glob'],
    suppressIfDeps: ['fast-glob', 'tinyglobby', 'globby', 'glob', 'fdir', 'readdirp'],
    note: 'Node 22+ has fs.promises.glob built in. Hand-rolled walks usually forget symlink cycles, .gitignore rules, and EACCES handling.',
    baseConfidence: 'low',
  },
];
