import { JS, type Detector } from '../detector-types.ts';

/** Object and function utilities that already exist as one-line imports (or as platform built-ins). */
export const UTIL_DETECTORS: Detector[] = [
  {
    id: 'deep-clone',
    capability: 'deep cloning objects',
    ext: JS,
    signals: [{ name: 'json-roundtrip', re: /JSON\.parse\(\s*JSON\.stringify\(/ }],
    minSignals: 1,
    decisive: ['json-roundtrip'],
    searchTerms: ['structuredClone alternative deep clone'],
    knownSolutions: ['structuredClone (Node built-in)', 'klona', 'rfdc'],
    suppressIfDeps: ['klona', 'rfdc', 'just-clone'],
    note: 'CORRECTNESS: the JSON round-trip silently destroys Date, Map, Set, BigInt, undefined, RegExp and cyclic references. structuredClone() is a global in Node 17+ and needs no dependency at all.',
    baseConfidence: 'high',
  },
  {
    id: 'deep-equal',
    capability: 'deep equality comparison',
    ext: JS,
    signals: [
      { name: 'fn-name', re: /\b(deepEqual|isEqual|deepCompare|objectsEqual|isDeepEqual)\b/ },
      { name: 'keys-walk', re: /Object\.keys\(|Object\.entries\(/ },
      { name: 'typeof-guard', re: /typeof\s+\w+\s*(===|!==)\s*['"`]object['"`]/ },
    ],
    minSignals: 2,
    required: ['fn-name'],
    searchTerms: ['fast deep equal javascript'],
    knownSolutions: ['fast-deep-equal', 'dequal'],
    suppressIfDeps: ['fast-deep-equal', 'dequal', 'deep-equal', 'lodash', 'lodash.isequal', 'es-toolkit'],
    baseConfidence: 'medium',
  },
  {
    id: 'deep-merge',
    capability: 'deep merging objects / applying config defaults',
    ext: JS,
    signals: [
      { name: 'fn-name', re: /\b(deepMerge|mergeDeep|deepAssign|mergeConfig|applyDefaults|withDefaults)\b/ },
      { name: 'is-object', re: /typeof\s+\w+\s*===\s*['"`]object['"`]/ },
      { name: 'spread-or-assign', re: /\.\.\.\w+|Object\.assign\(/ },
    ],
    minSignals: 2,
    required: ['fn-name'],
    searchTerms: ['deep merge config defaults library'],
    knownSolutions: ['defu', 'deepmerge-ts', 'deepmerge'],
    suppressIfDeps: ['defu', 'deepmerge', 'deepmerge-ts', 'lodash', 'lodash.merge', 'ts-deepmerge', 'es-toolkit'],
    note: 'SECURITY: hand-rolled recursive merges are the standard prototype-pollution sink -- merging attacker-controlled JSON containing __proto__ or constructor can poison Object.prototype. They also tend to get array strategy and Map/Set/Date handling wrong.',
    baseConfidence: 'low',
  },
  {
    id: 'debounce-throttle',
    capability: 'debounce / throttle',
    ext: JS,
    signals: [
      { name: 'name', re: /\b(debounce|throttle)\b/ },
      { name: 'timer', re: /setTimeout\s*\(|clearTimeout\s*\(/ },
      { name: 'closure-timer-var', re: /\b(timer|timeoutId|handle)\s*[:=]/ },
    ],
    minSignals: 2,
    required: ['name'],
    searchTerms: ['debounce throttle utility library'],
    knownSolutions: ['es-toolkit', 'throttle-debounce', 'lodash.debounce'],
    suppressIfDeps: ['es-toolkit', 'lodash', 'lodash.debounce', 'lodash.throttle', 'throttle-debounce', 'radash'],
    note: 'Hand-rolled debounce typically lacks leading/trailing edge control, cancel(), flush(), and a promise-returning variant.',
    baseConfidence: 'medium',
  },
  {
    id: 'event-emitter',
    capability: 'event emitter / pub-sub',
    ext: JS,
    signals: [
      { name: 'registry', re: /\b(listeners|subscribers|handlers|_events)\b\s*[:=]\s*(\[|new Map|new Set|\{)/ },
      { name: 'emit-api', re: /\b(emit|publish|dispatch)\s*\(/ },
      { name: 'subscribe-api', re: /\b(on|off|once|subscribe|unsubscribe|addListener)\s*\(/ },
    ],
    minSignals: 3,
    required: ['registry'],
    searchTerms: ['tiny event emitter library'],
    knownSolutions: ['node:events EventEmitter (built-in)', 'mitt', 'nanoevents', 'eventemitter3'],
    suppressIfDeps: ['mitt', 'nanoevents', 'eventemitter3', 'emittery', 'tseep'],
    note: "Node's built-in EventEmitter already handles once(), error routing, max-listener leak warnings, and async iteration via events.on().",
    baseConfidence: 'low',
  },
];
